const modalActionTypes = {
  SHOW_DELETE_MODAL: 'SHOW_DELETE_MODAL',
  SHOW_MAP_MODAL: 'SHOW_MAP_MODAL',
  HIDE_DELETE_MODAL: 'HIDE_DELETE_MODAL',
  HIDE_MAP_MODAL: 'HIDE_MAP_MODAL',
};

export default modalActionTypes;
